/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string>
#include "android/log.h"
#include "android/bitmap.h"
#include "opencv2/opencv.hpp"
#include "utils.h"
/* Header for class com_example_opencvtestapplication_MainActivity */
#define  LOG_TAG    "OpenCvTest"
#define  LOGI(...)  __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
#ifndef _Included_com_example_opencvtestapplication_MainActivity
#define _Included_com_example_opencvtestapplication_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT jobject JNICALL Java_com_example_opencvtestapplication_MainActivity_findIdNumber
        (JNIEnv *, jobject, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
